<form action="<?= $this->form->getAction(); ?>" name="UserForm" id="UserForm" method="post">

<div id="content-panel">

    <h2>
        <?= $this->user->isNew() ? 'Add user' : 'Edit user'; ?>
    </h2>

    <div class="form-panel">
        <?= $this->form->id; ?>
        <?= $this->form->username; ?>
        <?= $this->form->displayname; ?>
        <?= $this->form->password; ?>
        <?= $this->form->password_confirm; ?>
    </div>
    
</div>

<div id="sidebar-panel">

    <h2>Actions</h2>

    <ul class="actions">
        <li class="last">
            <input type="submit" value="Save" />
        </li>
    </ul>

    <hr />

    <ul class="actions">
        <?php if (!$this->user->isNew()) : ?>
        <li class="no-bg right">
            <?= $this->link(
                    '@admin_users_delete?id=' . $this->user->id,
                    $this->image($this->assetUrl('/images/icon/user--minus.png', false)) . ' delete user',
                    array(
                        'class' => 'delete',
                        'confirm' => 'Are you sure you want to delete this user?',
                        'escape' => false
                    )
            ); ?>
        </li>
        <?php endif; ?>
        <li class="no-bg right last">
            <?= $this->link(
                '@admin_users',
                $this->image($this->assetUrl('/images/icon/edit-list.png', false)) . ' back to users',
                array (
                    'escape' => false
                )
            ); ?>
        </li>
    </ul>
</div>

</form>