<div id="content-panel">
    <h2>Users</h2>
    
    <table class="data">
        <thead>
            <tr>
                <td>&nbsp;</td>
                <td>Username</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->users as $user) : ?>
            <tr>
                <td class="controls">
                    <?= $this->link(
                        "/fizzy/user/edit/{$user['id']}",
                        $this->image('/fizzy_assets/images/icon/user--pencil.png', array('alt' => 'edit icon')),
                        array (
                            'escape' => false
                        )
                    ); ?>
                </td>
                <td><?= $user['username'] ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div id="sidebar-panel">

    <h2>Actions</h2>

    <ul class="actions">
        <li class="last">
            <?= $this->link('/fizzy/user/add', $this->image('/fizzy_assets/images/icon/user--plus.png') . ' Add user', array('escape' => false)); ?>
        </li>
    </ul>


</div>
