<?php
/**
 * Admin layout
 * @package Fizzy
 * @subpackage Views
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.voidwalkers.nl/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@voidwalkers.nl so we can send you a copy immediately.
 *
 * @copyright Copyright (c) 2009 Voidwalkers (http://www.voidwalkers.nl)
 * @license http://www.voidwalkers.nl/license/new-bsd The New BSD License
 */
 ?>
<html>
    <head>
        <title>Fizzy Admin</title>
        <link href="<?= $this->url("/css/admin-screen.css") ?>" rel="stylesheet" type="text/css" media="screen" />
        <link href="<?= $this->url("/css/admin.css") ?>" rel="stylesheet" type="text/css" media="screen" />
        <script type="text/javascript" src="<?= $this->url("/js/yui-min.js"); ?>"></script>
    </head>
    <body>
            
        <div id="header">
            <div class="container">
                <div id="navigation" class="span-24 last">
                    <ul>
                        <li><a href="<?= $this->url("/admin/pages") ?>">Pages</a></li>
                        <li><a href="<?= $this->url("/admin/media") ?>">Media</a></li>
                        <!-- not implemented yet
                        <li><a href="<?= $this->url("/admin/menu") ?>">Menu</a></li>
                        -->
                        <li><a href="<?= $this->url("/admin/users") ?>">Users</a></li>
                        <li><a href="<?= $this->url("/admin/configuration") ?>">Configuration</a></li>
                        <li class="link-logout"><a href="<?= $this->url("/admin/logout") ?>">Logout</a></li>
                    </ul>
                    <div class="clear"></div>
                </div>
            </div>
        </div>

        <div class="container">

            <div id="content" class="span-24 last content-container">
                <div id="content-wrapper">
                    <?= $this->content ?>
                </div>
            </div>

            <div id="footer" class="span-24 last">
                (c) 2009 Voidwalkers - <a href="http://www.voidwalkers.nl/license/new-bsd">license</a>
            </div>
        </div>

        <div class="clear"></div>
    </body>
</html>
