<html>
    <head>
        <title>Fizzy Admin</title>
        <link href="<?= $this->url("/css/admin-screen.css") ?>" rel="stylesheet" type="text/css" media="screen" />
        <link href="<?= $this->url("/css/admin.css") ?>" rel="stylesheet" type="text/css" media="screen" />
        <link href="<?= $this->url("/js/yui/build/assets/skins/sam/skin.css") ?>" rel="stylesheet"  type="text/css" media="screen" />
        <script type="text/javascript" src="<?= $this->url("/js/yui/build/yahoo-dom-event/yahoo-dom-event.js"); ?>"></script>
        <script type="text/javascript" src="<?= $this->url("/js/yui/build/element/element-min.js"); ?>"></script>
    </head>
    <body>
            
        <div id="header">
            <div class="container">
                <div id="navigation" class="span-24 last">
                    <ul>
                        <li><a href="<?= $this->url("/admin/pages") ?>">Pages</a></li>
                        <!-- not implemented yet
                        <li><a href="<?= $this->url("/admin/menu") ?>">Menu</a></li>
                        -->
                        <li><a href="<?= $this->url("/admin/users") ?>">Users</a></li>
                        <li><a href="<?= $this->url("/admin/configuration") ?>">Configuration</a></li>
                        <li class="link-logout"><a href="<?= $this->url("/admin/logout") ?>">Logout</a></li>
                    </ul>
                    <div class="clear"></div>
                </div>
            </div>
        </div>

        <div class="container">

            <div id="content" class="span-24 last content-container">
                <div id="content-wrapper">
                    <?= $this->content ?>
                </div>
            </div>

            <div id="footer" class="span-24 last">
                (c) 2009 Voidwalkers - <a href="http://www.voidwalkers.nl/license/new-bsd">license</a>
            </div>
        </div>

        <div class="clear"></div>
    </body>
</html>
