<html>
    <head>
        <?php 
            $application = Fizzy_Config::getInstance()->getSection(Fizzy_Config::SECTION_APPLICATION);
            $title = $application['title'];
         ?>
        <title><?= $title; ?></title>
        <link href="<?= $this->url("/css/default-screen.css") ?>" rel="stylesheet" type="text/css" media="screen" />
        <link href="<?= $this->url("/css/default.css") ?>" rel="stylesheet" type="text/css" media="screen" />
    </head>
    <body>

        <div class="container">

            <!-- HEADER -->
            <div id="header" class="span-24 last">
                <h1>Fizzy<span>CMS</span></h1>
            </div>

            <!-- NAVIGATION -->
            <div id="navigation" class="span-24 last">
                <ul>
                    <li><a href="/">Home</a></li>
                    <li><a href="/about">About</a></li>
                    <li><a href="/configuration">Configuration</a></li>
                    <li><a href="http://project.voidwalkers.nl/projects/show/fizzy" target="_blanc">More</a></li>
               </ul>
            </div>

            <!-- CONTENT -->
            <div id="main-wrapper" class="span-24 last">
                <div id="content" class="span-24">
                    <div class="content-block">
                        <?= $this->content; ?>
                    </div>
                </div>
            </div>

            <!-- FOOTER -->
            <div id="footer" class="span-24 last">
                (c) 2009 <a href="http://www.voidwalkers.nl" title="The Voidwalkers">Voidwalkers</a> - <a href="http://www.voidwalkers.nl/license/bsd-license" title="Fizzy license">license</a>
            </div>

        </div>

    </body>
</html>