<?php
/**
 * Fizzy layout
 * @package Fizzy
 * @subpackage Views
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.voidwalkers.nl/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@voidwalkers.nl so we can send you a copy immediately.
 *
 * @copyright Copyright (c) 2009 Voidwalkers (http://www.voidwalkers.nl)
 * @license http://www.voidwalkers.nl/license/new-bsd The New BSD License
 */
 ?>
 <!DOCTYPE html>
<html>
    <head>
        <title>Fizzy</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link href="<?= $this->baseUrl("/fizzy_assets/css/reset-min.css") ?>" rel="stylesheet" type="text/css" media="screen, presentation" />
        <link href="<?= $this->baseUrl("/fizzy_assets/css/fonts-min.css") ?>" rel="stylesheet" type="text/css" media="screen, presentation" />
        <link href="<?= $this->baseUrl("/fizzy_assets/css/fizzy-2.0.css") ?>" rel="stylesheet" type="text/css" media="screen, presentation" />
        <link href="<?= $this->baseUrl("/fizzy_assets/css/tables.css") ?>" rel="stylesheet" type="text/css" media="screen, presentation" />
        <link href="<?= $this->baseUrl("/fizzy_assets/css/forms.css") ?>" rel="stylesheet" type="text/css" media="screen, presentation" />
        <script type="text/javascript" src="<?= $this->baseUrl("/fizzy_assets/js/jquery-1.3.2.min.js"); ?>"></script>
        <script type="text/javascript" src="<?= $this->baseUrl('/fizzy_assets/js/tiny_mce/tiny_mce.js'); ?>"></script>
        <script type="text/javascript" src="<?= $this->baseUrl('/fizzy_assets/js/fizzy.js'); ?>"></script>
    </head>
    <body>
        <div id="container">
            
            <div id="header-panel">
                
                <h1>Fizzy</h1>

                <div id="navigation-panel">
                    <ul>
                        <li class="active"><a href="<?= $this->baseUrl("/fizzy/pages") ?>">Pages</a></li>
                        <li><a href="<?= $this->baseUrl("/fizzy/media") ?>">Media</a></li>
                        <li><a href="<?= $this->baseUrl("/fizzy/users") ?>">Users</a></li>
                        <li><a href="<?= $this->baseUrl("/fizzy/configuration") ?>">Configuration</a></li>
                        <li class="link-logout"><a href="<?= $this->baseUrl("/fizzy/logout") ?>">Logout</a></li>
                    </ul>
                    <div class="clear"></div>
                </div>

            </div>
            
            <div id="main-panel">
                
                <div id="messages-panel">
                    <?= $this->render('flashMessages.phtml'); ?>
                </div>

                <div id="sidebar-panel">

                </div>

                <div id="content-panel">
                    <?= $this->layout()->content; ?>
                </div>

                <div class="clear"></div>

            </div>

            <div id="footer-panel">
                
                <div id="copyright-panel">
                    (c) 2009-<?= date('Y'); ?> Voidwalkers - <a href="http://www.voidwalkers.nl/license/new-bsd">license</a>
                </div>

                <div class="clear"></div>
            </div>

        </div>
    </body>
</html>
