<div id="content-panel">
    <h2><?= $this->blog->name ?></h2>

    <div>
        <table class="data">
            <thead>
                <tr>
                    <td>&nbsp;</td>
                    <td><?= $this->translate('Title') ?></td>
                    <td><?= $this->translate('Date') ?></td>
                    <td><?= $this->translate('Status') ?></td>
                    <td><?= $this->translate('Author') ?></td>
                </tr>
            </thead>
            <tbody>
                <?php $items = $this->paginator->getCurrentItems();
                foreach ($items as $post): ?>
                <tr>
                    <td class="controls">
                        <?= $this->link('@admin_blog_post_edit?post_id=' . $post->id, $this->image($this->assetUrl('/images/icon/document--pencil.png', false), array('alt' => 'edit icon')), array('title' => $this->translate('edit page'), 'escape' => false)); ?>
                    </td>
                    <td>
                        <?= $post->title ?>
                    </td>
                    <td>
                        <?= $post->date ?>
                    </td>
                    <td>
                        <?php if ($post->status == Post::PUBLISHED): ?>
                        <?= $this->translate('Published') ?>
                        <?php elseif ($post->status == Post::PENDING_REVIEW): ?>
                        <?= $this->translate('Pending review') ?>
                        <?php else: ?>
                        <?= $this->translate('Draft') ?>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?= $post->User->displayname ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?= $this->paginationControl($this->paginator, 'All', '_pagination.phtml') ?>
    </div>
</div>

<div id="sidebar-panel">
    <h2><?= $this->translate('Actions') ?></h2>

    <ul class="actions">
        <li class="last">
            <?= $this->link('@admin_blog_post_add?blog_id=' . $this->blog->id, $this->image($this->assetUrl('/images/icon/document--plus.png', false)) . ' '.$this->translate('Add post'), array('escape' => false)); ?>
        </li>
    </ul>
</div>