<form action="<?= $this->form->getAction(); ?>" method="post" id="PageForm" name="PageForm">

    <div id="content-panel">
        <h2>
            <?= $this->image($this->assetUrl('/images/icon/document.png', false)); ?>
            <?= $this->translate($this->post->isNew() ? 'Add post' : 'Edit post') ?>
        </h2>

        <div class="form-panel">
                <?= $this->form->title; ?>
                <?= $this->form->body; ?>
        </div>

        <h2>
            <?= $this->image($this->assetUrl('/images/icon/balloons.png', false)); ?>
            <?= $this->translate('Comments on this post') ?>
        </h2>

        <div class="comments">
            <?= $this->partial('comments/_comments.phtml', array(
                'comments' => $this->post->Comments(),
                'back' => 'post'
            )) ?>
        </div>

    </div>

    <div id="sidebar-panel">
        <h2><?= $this->translate('Actions') ?></h2>

        <ul class="actions">
            <li class="last">
                <input type="submit" value="<?= $this->translate('Save') ?>" />
            </li>
        </ul>

        <hr />

        <ul class="actions">
            <?php if(!$this->post->isNew()) : ?>
            <li class="no-bg right">
                <?= $this->link(
                        '@admin_blog_post_delete?post_id=' . $this->post->id,
                        $this->image($this->assetUrl('/images/icon/document--minus.png', false)) . ' '.$this->translate('delete post'),
                        array(
                            'class' => 'delete',
                            'confirm' => $this->translate('Are you sure you want to delete this post?'),
                            'escape' => false
                       )
                ); ?>
            </li>
            <?php endif; ?>
            <li class="no-bg right last">
                <?= $this->link(
                    '@admin_blog?id=' . $this->post->Blog->id,
                    $this->image($this->assetUrl('/images/icon/edit-list.png', false)) . ' '.$this->translate('back to').' ' . $this->post->Blog->name,
                    array('escape' => false)
                ); ?>
            </li>
        </ul>

        <h2><?= $this->translate('Options') ?></h2>

        <div class="form-options-panel">
            <?= $this->form->status; ?>
            <?= $this->form->author; ?>
            <?= $this->form->date; ?>
            <?= $this->form->comments; ?>

        </div>

    </div>
</form>