<?php foreach ($this->posts as $post): ?>
<div>
    <div><?= $post->title ?></div>
    <div><?= $post->date ?> - <?= $post->User->displayname ?></div>
    <div><?= $post->body ?></div>
    <div>
        <div>Comments:</div>
        <?php foreach ($post->comments() as $comment): ?>
        <div><?= $comment->name ?> - <?= $comment->date ?></div>
        <div><?= $comment->body ?></div>
        <?php endforeach; ?>
    </div>
</div>
<?php endforeach; ?>