<?php
$types = array(
    'png' => $this->assetUrl('/images/icon/page_white_picture.png'),
    'jpg' => $this->assetUrl('/images/icon/page_white_picture.png'),
    'jpeg' => $this->assetUrl('/images/icon/page_white_picture.png'),
    'bmp' => $this->assetUrl('/images/icon/page_white_picture.png'),
    'gif' => $this->assetUrl('/images/icon/page_white_picture.png'),
    'doc' => $this->assetUrl('/images/icon/page_white_word.png'),
    'docx' => $this->assetUrl('/images/icon/page_white_word.png'),
    'xls' => $this->assetUrl('/images/icon/page_white_excel.png'),
    'ppt' => $this->assetUrl('/images/icon/page_white_powerpoint.png'),
    'pdf' => $this->assetUrl('/images/icon/page_white_text.png'),
    'flv' => $this->assetUrl('/images/icon/page_white_flash.png'),
    'zip' => $this->assetUrl('/images/icon/page_white_zip.png'),
    'rar' => $this->assetUrl('/images/icon/page_white_zip.png'),
    'txt' => $this->assetUrl('/images/icon/page_white_text.png'),
);
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>{#fizzyassets_dlg.title}</title>
    <link href="<?= $this->assetUrl("/css/fizzy.css") ?>" rel="stylesheet" type="text/css" media="screen" />
    <script type="text/javascript" src="<?= $this->assetUrl('/js/tiny_mce/tiny_mce_popup.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->assetUrl('/js/tiny_mce/plugins/fizzyassets/js/dialog.js') ?>"></script>
</head>
<body>

<div id="image-picker" class="files-container">
    <table class="files-table">
        <thead>
            <tr>
                <td colspan="2">Filename</td>
                <td>Size</td>
            </tr>
        </thead>
        <tbody>
    <?php foreach($this->files as $fileInfo) : ?>
        <tr id="<?= $this->baseUrl('/uploads/' . $fileInfo->basename); ?>">
            <td class="icon"><img src="<?= (array_key_exists($fileInfo->type, $types)) ? $types[$fileInfo->type] : $this->assetUrl('/images/icon/page.png'); ?>" alt="" /></td>
            <td class="filename">
                <a href="#" onclick="select('<?= $this->baseUrl('/uploads/' . $fileInfo->basename); ?>', this.parentNode.parentNode);">
                <?php if (strlen($fileInfo->basename) > 14):?>
                    <?= substr($fileInfo->basename, 0, 14); ?>...
                <?php else: ?>
                    <?= $fileInfo->basename ?>
                <?php endif; ?>
                </a>
            </td>
            <td class="size">
                <?php if($fileInfo->size < 1024) : ?>
                <?= round($fileInfo->size, 2); ?> b
                <?php elseif((1024*1024) > $fileInfo->size) : ?>
                <?= round($fileInfo->size / 1024, 2); ?> KB
                <?php else : ?>
                <?= round($fileInfo->size / (1024*1024), 2); ?> MB
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
        </tbody>
    </table>
    
</div>
<form onsubmit="FizzyassetsDialog.insert();return false;" action="#">
<div>
    <div class="form-left">
        <label>Description:</label>
            <input type="text" name="alt" id="alt" />
    </div>
    
<div class="clear"></div>
    <input type="button" name="insert" value="{#insert}" onclick="FizzyassetsDialog.insert();" />
    <input type="button" name="cancel" value="{#cancel}" onclick="tinyMCEPopup.close();" />
</div>
</form>

</body>
</html>
