<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>{#fizzymedia_dlg.title}</title>
    <link href="<?= $this->assetUrl("/css/fizzy.css") ?>" rel="stylesheet" type="text/css" media="screen" />
    <script type="text/javascript" src="<?= $this->assetUrl('/js/tiny_mce/tiny_mce_popup.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->assetUrl('/js/tiny_mce/plugins/fizzymedia/js/dialog.js') ?>"></script>
</head>
<body>

<div id="image-picker" class="files-container">
    <?php foreach($this->files as $fileInfo) : ?>
    <div class="thumbnail" id="<?= $this->baseUrl('/uploads/' . $fileInfo->basename); ?>" onclick="select('<?= $this->baseUrl('/uploads/' . $fileInfo->basename); ?>', this);">
        <img class="thumbnail" src="<?= $this->baseUrl('/uploads/' . $fileInfo->basename); ?>" alt="<?= $fileInfo->basename ?>" />
        
        <div class="filename">
            <?php if (strlen($fileInfo->basename) > 14):?>
                <?= substr($fileInfo->basename, 0, 14); ?>...
            <?php else: ?>
                <?= $fileInfo->basename ?>
            <?php endif; ?>
        </div>
        <div class="size">
            <?php if($fileInfo->size < 1024) : ?>
            <?= round($fileInfo->size, 2); ?> b
            <?php elseif((1024*1024) > $fileInfo->size) : ?>
            <?= round($fileInfo->size / 1024, 2); ?> KB
            <?php else : ?>
            <?= round($fileInfo->size / (1024*1024), 2); ?> MB
            <?php endif; ?>
        </div>
    </div>
    <?php endforeach; ?>

    
</div>
<form onsubmit="FizzymediaDialog.insert();return false;" action="#">
<div>
    <div class="form-left">
        <label>Description:</label>
            <input type="text" name="alt" id="alt" />
        <label>Width</label>
            <input type="text" name="width" id="width" class="small" /> px
        <label>Height</label>
            <input type="text" name="height" id="height" class="small" /> px
        <label>Alignment</label>
            <select name="position" id="position">
                <option value="none">-- Not Set --</option>
                <option value="left">Left</option>
                <option value="right">Right</option>
                <option value="baseline">Baseline</option>
                <option value="top">Top</option>
                <option value="middle">Middle</option>
                <option value="bottom">Bottom</option>
                <option value="text-top">Text top</option>
                <option value="text-bottom">Text bottom</option>
            </select>

        <label>Border</label>
            <input type="text" name="border" id="border" class="small" /> px
    </div>
    <div class="form-right">
        <label>Margins</label>
            <table>
                <tr>
                    <td></td>
                    <td> <input type="text" name="marginTop" id="marginTop" /></td>
                    <td></td>
                </tr>
                <tr>
                    <td><input type="text" name="marginLeft" id="marginLeft" /></td>
                    <td class="center"><img src="<?= $this->assetUrl('/js/tiny_mce/plugins/fizzymedia/img/flower.png');?>" alt="flower"  /></td>
                    <td><input type="text" name="marginRight" id="marginRight" /></td>
                </tr>
                <tr>
                    <td></td>
                    <td> <input type="text" name="marginBottom" id="marginBottom" /></td>
                    <td></td>
                </tr>
            </table>
        <p>You can specify the margins around the picture above.</p>
    </div>
    
<div class="clear"></div>
    <input type="button" name="insert" value="{#insert}" onclick="FizzymediaDialog.insert();" />
    <input type="button" name="cancel" value="{#cancel}" onclick="tinyMCEPopup.close();" />
</div>
</form>

</body>
</html>
