<?php
$types = array(
    'png' => $this->assetUrl('/images/icon/page_white_picture.png'),
    'jpg' => $this->assetUrl('/images/icon/page_white_picture.png'),
    'jpeg' => $this->assetUrl('/images/icon/page_white_picture.png'),
    'bmp' => $this->assetUrl('/images/icon/page_white_picture.png'),
    'gif' => $this->assetUrl('/images/icon/page_white_picture.png'),
    'doc' => $this->assetUrl('/images/icon/page_white_word.png'),
    'docx' => $this->assetUrl('/images/icon/page_white_word.png'),
    'xls' => $this->assetUrl('/images/icon/page_white_excel.png'),
    'ppt' => $this->assetUrl('/images/icon/page_white_powerpoint.png'),
    'pdf' => $this->assetUrl('/images/icon/page_white_text.png'),
    'flv' => $this->assetUrl('/images/icon/page_white_flash.png'),
    'zip' => $this->assetUrl('/images/icon/page_white_zip.png'),
    'rar' => $this->assetUrl('/images/icon/page_white_zip.png'),
    'txt' => $this->assetUrl('/images/icon/page_white_text.png'),
);
?>

<div class="media-container">
    <table class="media">
        <?php if(0 < count($this->files)) : ?>
        <tbody>
            <?php $row = 0; foreach($this->files as $fileInfo) : ?>
            <tr class="<?= (++$row % 2) === 0 ? 'even' : 'odd'; ?>">
                <td class="icon">
                    <img src="<?= (array_key_exists($fileInfo->type, $types)) ? $types[$fileInfo->type] : $this->baseUrl('/images/icon/page.png'); ?>" alt="" />
                </td>
                <td class="filename">
                    <a href="<?= $this->baseUrl('/uploads/' . $fileInfo->basename); ?>" target="_blank" title="View file">
                        <?= $fileInfo->basename; ?>
                    </a>
                </td>
                <td class="size">
                <?php if($fileInfo->size < 1024) : ?>
                <?= round($fileInfo->size, 2); ?> b
                <?php elseif((1024*1024) > $fileInfo->size) : ?>
                <?= round($fileInfo->size / 1024, 2); ?> KB
                <?php else : ?>
                <?= round($fileInfo->size / (1024*1024), 2); ?> MB
                <?php endif; ?>
                <td class="controls">
                    <?php if(is_writable($this->uploadFolder)) : ?>
                    <?= $this->link(
                        '@admin_media_delete?name=' . urlencode($fileInfo->basename),
                        $this->image($this->assetUrl('/images/icon/minus-small.png')),
                        array (
                            'confirm' => "Are you sure you want to delete {$fileInfo->basename}?",
                            'title' => 'Delete file',
                            'escape' => false,
                        )
                    ); ?>
                    <?php endif; ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
        <?php else : ?>
        <tr>
            <td colspan="4">
                No uploaded files were found. Use the form at the bottom to
                add new files.
            </td>
        </tr>
        <?php endif; ?>
    </table>
</div>