<?php
$types = array(
    'png' => $this->baseUrl('/fizzy_assets/images/icon/page_white_picture.png'),
    'jpg' => $this->baseUrl('/fizzy_assets/images/icon/page_white_picture.png'),
    'jpeg' => $this->baseUrl('/fizzy_assets/images/icon/page_white_picture.png'),
    'bmp' => $this->baseUrl('/fizzy_assets/images/icon/page_white_picture.png'),
    'gif' => $this->baseUrl('/fizzy_assets/images/icon/page_white_picture.png'),
    'doc' => $this->baseUrl('/fizzy_assets/images/icon/page_white_word.png'),
    'docx' => $this->baseUrl('/fizzy_assets/images/icon/page_white_word.png'),
    'xls' => $this->baseUrl('/fizzy_assets/images/icon/page_white_excel.png'),
    'ppt' => $this->baseUrl('/fizzy_assets/images/icon/page_white_powerpoint.png'),
    'pdf' => $this->baseUrl('/fizzy_assets/images/icon/page_white_text.png'),
    'flv' => $this->baseUrl('/fizzy_assets/images/icon/page_white_flash.png'),
    'zip' => $this->baseUrl('/fizzy_assets/images/icon/page_white_zip.png'),
    'rar' => $this->baseUrl('/fizzy_assets/images/icon/page_white_zip.png'),
    'txt' => $this->baseUrl('/fizzy_assets/images/icon/page_white_text.png'),
);
?>
<div class="files-container">
    <table class="files-table">
        <?php if(0 < count($this->files)) : ?>
        <thead>
            <tr>
                <td colspan="2">Filename</td>
                <td>Size</td>
                <td>&nbsp;</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->files as $fileInfo) : ?>
            <tr>
                <td class="icon">
                    <img src="<?= (array_key_exists($fileInfo->type, $types)) ? $types[$fileInfo->type] : $this->baseUrl('/images/icon/page.png'); ?>" alt="" />
                </td>
                <td class="filename">
                    <?= $fileInfo->basename; ?>
                </td>
                <td class="size">
                <?php if($fileInfo->size < 1024) : ?>
                <?= round($fileInfo->size, 2); ?> b
                <?php elseif((1024*1024) > $fileInfo->size) : ?>
                <?= round($fileInfo->size / 1024, 2); ?> KB
                <?php else : ?>
                <?= round($fileInfo->size / (1024*1024), 2); ?> MB
                <?php endif; ?>
                <td class="controls">
                    <a href="<?= $this->baseUrl('/uploads/' . $fileInfo->basename); ?>" target="_blank" title="View file"><?= $this->img('/fizzy_assets/images/icon/view.png'); ?></a>
                    <?php if(is_writable($this->uploadFolder)) : ?>
                    <?= $this->linkConfirm('/fizzy/media/delete/' . urlencode($fileInfo->basename), $this->img('/fizzy_assets/images/icon/delete.png'), "Are you sure you want to delete {$fileInfo->basename}?", array('title' => 'Delete file')); ?>
                    <?php endif; ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
        <?php else : ?>
        <tr>
            <td>
                No uploaded files were found. Use the form at the bottom to
                add new files.
            </td>
        </tr>
        <?php endif; ?>
    </table>
</div>