<?php
// file type image declarations

$images = array('png', 'jpg', 'jpeg', 'bmp', 'gif');

$types = array(
    'png' => $this->baseUrl('/fizzy_assets/images/mimetypes/png.png'),
    'jpg' => $this->baseUrl('/fizzy_assets/images/mimetypes/jpg.png'),
    'jpeg' => $this->baseUrl('/fizzy_assets/images/mimetypes/jpg.png'),
    'bmp' => $this->baseUrl('/fizzy_assets/images/mimetypes/bmp.png'),
    'gif' => $this->baseUrl('/fizzy_assets/images/mimetypes/gif.png'),
    'doc' => $this->baseUrl('/fizzy_assets/images/mimetypes/doc.png'),
    'docx' => $this->baseUrl('/fizzy_assets/images/mimetypes/doc.png'),
    'xls' => $this->baseUrl('/fizzy_assets/images/mimetypes/xls.png'),
    'ppt' => $this->baseUrl('/fizzy_assets/images/mimetypes/ppt.png'),
    'pdf' => $this->baseUrl('/fizzy_assets/images/mimetypes/pdf.png'),
    'flv' => $this->baseUrl('/fizzy_assets/images/mimetypes/flv.png'),
    'zip' => $this->baseUrl('/fizzy_assets/images/mimetypes/zip.png'),
    'rar' => $this->baseUrl('/fizzy_assets/images/mimetypes/rar.png'),
    'txt' => $this->baseUrl('/fizzy_assets/images/mimetypes/txt.png'),
);
?>

<div class="media-container">
    
    <?php foreach($this->files as $fileInfo) : ?>
    <div class="thumbnail">

        <div class="head">
            <span class="filename">
                <?php if (strlen($fileInfo->basename) > 14):?>
                    <?= substr($fileInfo->basename, 0, 14); ?>...
                <?php else: ?>
                    <?= $fileInfo->basename ?>
                <?php endif; ?>
            </span>
            <?php if(is_writable($this->uploadFolder)) : ?>
            <span class="remove">
                <?= $this->link(
                    '/fizzy_assets/media/delete/' . urlencode($fileInfo->basename),
                    $this->image('/fizzy_assets/images/icon/cross-small.png'),
                    array (
                        'confirm' => "Are you sure you want to delete {$fileInfo->basename}?",
                        'title' => 'Delete file',
                        'escape' => false,
                    )
                ); ?>
            </span>
            <?php endif; ?>
            <div class="clear"></div>
        </div>

        <div class="body">
            <a href="<?= $this->baseUrl('/uploads/' . $fileInfo->basename); ?>" target="_blank" title="View file">
            <?php if (in_array($fileInfo->type, $images)): ?>
                <img class="source" src="<?= $this->baseUrl('/uploads/' . $fileInfo->basename); ?>" alt="<?= $fileInfo->basename ?>" />
            <?php else: ?>
                <img class="icon" width="48px" height="48px" src="<?= (array_key_exists($fileInfo->type, $types)) ? $types[$fileInfo->type] : $this->baseUrl('/fizzy_assets/images/icon/page.png'); ?>" alt="" />
            <?php endif; ?>
            </a>
        </div>
        
        <div class="foot">
            <span class="size">
                <?php if($fileInfo->size < 1024) : ?>
                <?= round($fileInfo->size, 2); ?> b
                <?php elseif((1024*1024) > $fileInfo->size) : ?>
                <?= round($fileInfo->size / 1024, 2); ?> KB
                <?php else : ?>
                <?= round($fileInfo->size / (1024*1024), 2); ?> MB
                <?php endif; ?>
            </span>

            <div class="clear"></div>
        </div>
    </div>
    <?php endforeach; ?>
    <div class="clear"></div>
</div>