<div id="content-panel">
    <h2>Contact</h2>

    <table class="data" id="contact-table">
        <thead>
            <tr>
                <th>&nbsp;</th>
                <th>Date</th>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->messages as $message) : ?>
            <tr>
                <td class="controls" style="width: 55px;">
                    <?= $this->link('@admin_contact_show?id=' . $message->id, $this->image($this->assetUrl('/images/icon/mail-open.png')), array('escape' => false)); ?>
                    &nbsp;
                    <?= $this->link(
                        '@admin_contact_delete?id=' . $message->id,
                        $this->image($this->assetUrl('/images/icon/mail--minus.png')),
                        array (
                            'confirm' => 'Are you sure you want to delete this contact request?',
                            'escape' => false
                        )
                    ); ?>
                </td>
                <td style="width: 150px;"><?= $message->date; ?></td>
                <td style="max-width: 300px;"><?= $message->name; ?> &lt;<a href="mailto:<?= $message->email; ?>"><?= $message->email; ?></a>&gt;</td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div id="sidebar-panel">
    
</div>