<div id="content-panel">
    <h2>Contact</h2>

    <table class="data" id="contact-table">
        <thead>
            <tr>
                <th>&nbsp;</th>
                <th>Date</th>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->messages as $message) : ?>
            <tr>
                <td class="controls" style="width: 55px;">
                    <?= $this->link('/fizzy/contact/show/' . $message->id, $this->img('/fizzy_assets/images/icon/mail-open.png')); ?>
                    &nbsp;
                    <?= $this->linkConfirm('/fizzy/contact/delete/' . $message->id, $this->img('/fizzy_assets/images/icon/mail--minus.png'), 'Are you sure you want to delete this contact request?'); ?>
                </td>
                <td style="width: 150px;"><?= $message->date; ?></td>
                <td style="max-width: 300px;"><?= $message->name; ?> &lt;<a href="mailto:<?= $message->email; ?>"><?= $message->email; ?></a>&gt;</td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div id="sidebar-panel">
    
</div>