<div id="content-panel">
    <h2>Contact request</h2>

    <p>
        From: <?= $this->message->name; ?> &lt;<a href="mailto:<?= $this->message->email; ?>"><?= $this->message->email; ?></a>&gt;<br />
        On:   <?= $this->message->date; ?>
    </p>

    <p>
        <?= nl2br($this->message->body); ?>
    </p>
</div>

<div id="sidebar-panel">
    <h2>Actions</h2>

    <ul class="actions">
        <li class="no-bg right">
            <?= $this->link(
                    '@admin_contact_delete?id=' . $this->message->id,
                    $this->image($this->assetUrl('/images/icon/mail--minus.png')) . 'delete message',
                    array(
                        'class' => 'delete',
                        'confirm' => 'Are you sure you want to delete this message?',
                        'escape' => false
                    )
            ); ?>
        </li>
        <li class="no-bg right last">
            <?= $this->link('@admin_contact', $this->image($this->assetUrl('/images/icon/edit-list.png')) . ' contact list', array('escape' => false)); ?>
        </li>
    </ul>
</div>