<?php
/**
 * Login view
 * @package Fizzy
 * @subpackage Views
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.voidwalkers.nl/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@voidwalkers.nl so we can send you a copy immediately.
 *
 * @copyright Copyright (c) 2009 Voidwalkers (http://www.voidwalkers.nl)
 * @license http://www.voidwalkers.nl/license/new-bsd The New BSD License
 */
 ?>
<html>
    <head>
        <title>Fizzy - Login</title>
        <link href="<?= $this->url("/admin/css/admin.css") ?>" rel="stylesheet" type="text/css" media="screen" />
    </head>
    <body>

        <div class="span-12 push-10 container last">
            
            <div id="content" class="content-container login-container">
                <div id="content-wrapper">
                    <h1>Fizzy</h1>

                    <div class="form-container">
                        <?php if (!empty($this->message)) : ?>
                        <span class="error"><?= $this->message ?></span>
                        <?php endif; ?>
                        <form action="<?= $this->url ?>" method="POST">

                            <div class="form-row">
                                <label for="username">username</label>
                                <input type="text" name="username" />
                            </div>

                            <div class="form-row">
                                <label for="password">password</label>
                                <input type="password" name="password" />
                            </div>

                            <div class="form-row">
                                <input type="submit" value="Login" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div id="footer">
                Copyright (c) 2009 <a href="http://www.voidwalkers.nl" title="Voidwalkers website">Voidwalkers</a> - <a href="http://www.voidwalkers.nl/license/new-bsd" title="Fizzy license">license</a>
            </div>

        </div>

    </body>
</html>