<?php if (isset($this->previous)): ?>
  <a href="?page=<?= $this->previous ?>">
    &lt;&lt; <?= $this->translate('prev') ?>
  </a>
<?php else: ?>
  &lt;&lt; <?= $this->translate('prev') ?>
<?php endif; ?>

<?php foreach ($this->pagesInRange as $page): ?>
    <a href="?page=<?= $page ?>">
        <?= $page; ?>
    </a>
<?php endforeach; ?>
  
<?php if (isset($this->next)): ?>
  <a href="?page=<?= $this->next ?>">
      <?= $this->translate('next') ?> &gt;&gt;
  </a>
<?php else: ?>
  <?= $this->translate('next') ?> &gt;&gt;
<?php endif; ?>