<div id="content-panel">

    <h2>Media</h2>

    <div id="media-panel">
        <div id="media-tabs-panel">
            <?php
                $activeTab = isset($_GET['type']) ? $_GET['type'] : null;
            ?>
            <ul>
                <li>
                    Show as:
                </li>
                <li><a class="<?= 'thumbnail' != strtolower($_GET['type']) ? 'active' : ''; ?>" href="<?= $this->baseUrl('/admin/media') ?>">List</a></li>
                <li>&nbsp;|&nbsp;</li>
                <li><a class="<?= 'thumbnail' == strtolower($_GET['type']) ? 'active' : ''; ?>" href="<?= $this->baseUrl('/admin/media?type=thumbnail') ?>">Thumbnail</a></li>
            </ul>
            <div class="clear"></div>
        </div>
        <?= $this->action('display', 'media', 'admin', array('type' => $this->type)); ?>
    </div>

</div>

<div id="sidebar-panel">
    <div id="upload-form" class="form-container">
        <h2 class="header">Upload</h2>

        <p>
            Upload a new file by selecting it on your machine. Check the box if
            you want to overwrite a file that already exists with the same name.
            <br />

        </p>
        <?php if(is_writable($this->uploadFolder)) : ?>
        <?= $this->form; ?>
        <?php else : ?>
        <div class="message notice">
            <p>
                The upload directory found in the Fizzy configuration is not
                writable. Upload functionality will be disabled until it is made
                writable.
            </p>
        </div>
        <?php endif; ?>
    </div>
</div>