<ul>
    <?php foreach($this->items as $page) : ?>
        <?php $label = $page->getLabel();
        if (!empty($label)): ?>
            <li<?= ($page->isActive(true)) ? ' class="active"' : ''; ?>>
                <a href="<?= $page->getHref(); ?>"><?= $this->navigation()->getTranslator()->translate($page->getLabel()) ?></a>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>
<div class="clear"></div>