<div class="post">
    <h2>
        <?= $this->link(
                '@blog_post?blog_slug=' . $this->post->Blog->slug . '&post_slug=' . $this->post->slug,
                $this->post->title
        ); ?>
    </h2>
    <div class="post-meta-top">
        on <?= date('d-m-Y', strtotime($this->post->date)); ?>
        by <?= $this->link('@user_posts?username=' . $this->post->User->username,$this->post->User->displayname); ?>
        in <?= $this->link('@blog_posts?blog_slug=' . $this->post->Blog->slug, $this->post->Blog->name); ?>
    </div>

    <div class="post-intro">
        <?= $this->post->intro; ?>
    </div>

    <div class="post-body">
        <?= $this->post->body; ?>
    </div>
    
</div>

<div class="comments">
    <a name="comments"></a>
    
    <h3>Comments</h3>
    <?php if ($this->post->comments) : ?>
    <p>
        There are <?= count($this->post->comments()); ?> comments for this entry.
        <a href="#comment-form">Leave your own?</a>
    </p>
    
    <?= $this->commentStream('post:' . $this->post->id, 'blog/comments.phtml'); ?>

    <div class="comment-form">
        <h4>Leave a comment</h4>
        <a name="comment-form"></a>
        <form action="<?= $this->url('@add_comment?stream=post:' . $this->post->id); ?>" method="post" name="CommentForm">
            <div class="comment-form-row">
                <label for="name">Name *</label>
                <input type="text" name="name" />
            </div>

            <div class="comment-form-row">
                <label for="name">Email *</label>
                <input type="text" name="email" />
                <br /><small>Your email will not be published</small>
            </div>

            <div class="comment-form-row">
                <label for="name">Website</label>
                <input type="text" name="website" />
            </div>

            <div class="comment-form-row">
                <label for="body">Message *</label>
                <textarea name="body"></textarea>
                <br /><small>HTML is disabled</small>
            </div>
            
            <div class="comment-form-row">
                <br />
                <input type="submit" value="Send" />
                <input type="reset" value="clear" />
            </div>

        </form>
    </div>


    <?php else : ?>
    <p class="comments-disabled">
        Comments for this entry are disabled
    </p>
    <?php endif; ?>
</div>