<?php
/**
 * Default layout
 * @package Fizzy
 * @subpackage Views
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.voidwalkers.nl/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@voidwalkers.nl so we can send you a copy immediately.
 *
 * @copyright Copyright (c) 2009-2010 Voidwalkers (http://www.voidwalkers.nl)
 * @license http://www.voidwalkers.nl/license/new-bsd The New BSD License
 */
 ?>
<html>
    <head>
        <?php 
            $config = Zend_Registry::get('config');
            $title = $config->title;
         ?>
        <title><?= $title; ?></title>
        <link href="<?= $this->assetUrl("/css/reset-min.css") ?>" rel="stylesheet" type="text/css" media="screen, presentation" />
        <link href="<?= $this->baseUrl("/fizzy_assets/css/fonts-min.css") ?>" rel="stylesheet" type="text/css" media="screen, presentation" />
        <link href="<?= $this->baseUrl("/css/fizzy.css") ?>" rel="stylesheet" type="text/css" media="screen" />
        <link rel="alternate" type="application/rss+xml" title="RSS" href="<?= $this->url('@blog_rss') ?>">
        <link rel="alternate" type="application/atom+xml" title="Atom" href="<?= $this->url('@blog_atom') ?>">
    </head>
    <body>

        <div class="container">

            <!-- HEADER -->
            <div id="header-panel" class="span-24 last">
                <h1>Fizzy<span>CMS</span></h1>

                <!-- NAVIGATION -->
                <div id="navigation-panel">
                    <ul>
                        <li><a href="<?= $this->baseUrl('/') ?>" title="Website home">Home</a></li>
                        <li><a href="<?= $this->baseUrl('/blog') ?>" title="The blog">Blog</a></li>
                        <li><a href="<?= $this->baseUrl('/about'); ?>" title="About this site">About</a></li>
                        <li><a href="<?= $this->baseUrl('/configuration'); ?>" title="How to configure Fizzy">Configuration</a></li>
                        <li><a href="http://project.voidwalkers.nl/projects/show/fizzy" target="_blank" title="Learn more about the fizzy project (opens in a new window)">More</a></li>
                    </ul>
                    <div class="clear"></div>
                </div>
                <!-- NAVIGATION -->
            </div>

            <!-- CONTENT -->
            <div id="main-panel" class="span-24 last">
                <div id="content-panel">
                    <?= $this->layout()->content; ?>
                </div>
            </div>

            <!-- FOOTER -->
            <div id="footer-panel" class="span-24 last">
                <p>
                This site is powered by Fizzy <?= Fizzy_Version::VERSION ?>
                running on Zend Framework <?= Zend_Version::VERSION ?>
                and Doctrine <?= Doctrine::VERSION ?>
                </p>
                <p>
                    (c) 2009-<?= date('Y'); ?> Voidwalkers - <a href="http://www.voidwalkers.nl/license/new-bsd">license</a><br />
                </p>
            </div>

        </div>

    </body>
</html>
