<form action="<?= $this->form->getAction(); ?>" method="post" id="PageForm" name="PageForm">

<div id="content-panel">

    <h2>
        <?= $this->image('/fizzy_assets/images/icon/document.png'); ?>
        <?= ($this->page->isNew()) ? 'Add page' : 'Edit page'; ?>
    </h2>
    
    <div class="form-panel">
            <?= $this->form->title; ?>
            <?= $this->form->slug; ?>
            <?= $this->form->body; ?>
    </div>
</div>
<div id="sidebar-panel">

    <h2>Actions</h2>

    <ul class="actions">
        <li class="last">
            <input type="submit" value="Save" />
        </li>
    </ul>

    <hr />

    <ul class="actions">
        <?php if(!$this->page->isNew()) : ?>
        <li class="no-bg right">
            <?= $this->link(
                    '/fizzy/pages/delete/' . $this->page->id,
                    $this->image('fizzy_assets/images/icon/document--minus.png') . ' delete page',
                    array(
                        'class' => 'delete',
                        'confirm' => 'Are you sure you want to delete this page?',
                        'escape' => false
                    )
            ); ?>
        </li>
        <?php endif; ?>
        <li class="no-bg right last">
            <?= $this->link(
                '/fizzy/pages',
                $this->image('/fizzy_assets/images/icon/edit-list.png') . ' back to pages',
                array('escape' => false)
            ); ?>
        </li>
    </ul>

    <h2>Options</h2>

    <div class="form-options-panel">

        <?= $this->form->template; ?>
        <?= $this->form->layout; ?>

        <div class="form-row" id="homepage-row">
            <label for="homepage">Homepage</label>
            <?= $this->form->homepage->setDecorators(array('ViewHelper', 'Errors')); ?>
            <?= $this->form->homepage->getDescription(); ?>
        </div>

    </div>
    
</div>

</form>
