<form action="<?= $this->form->getAction(); ?>" method="post" id="PageForm" name="PageForm">

<div id="content-panel">

    <h2>
        <?= $this->image($this->assetUrl('/images/icon/document.png', false)); ?>
        <?= $this->translate(($this->page->isNew()) ? 'Add page' : 'Edit page') ?>
    </h2>
    
    <div class="form-panel">
            <?= $this->form->id; // required for slugunique validator ?>
            <?= $this->form->title; ?>
            <?= $this->form->slug; ?>
            <?= $this->form->body; ?>
    </div>
</div>
<div id="sidebar-panel">

    <h2><?= $this->translate('Actions') ?></h2>

    <ul class="actions">
        <li class="last">
            <input type="submit" value="<?= $this->translate('Save') ?>" />
        </li>
    </ul>

    <hr />

    <ul class="actions">
        <?php if(!$this->page->isNew()) : ?>
        <li class="no-bg right">
            <?= $this->link(
                    '@admin_pages_delete?id=' . $this->page->id,
                    $this->image($this->assetUrl('/images/icon/document--minus.png', false)) . ' '.$this->translate('delete page'),
                    array(
                        'class' => 'delete',
                        'confirm' => $this->translate('Are you sure you want to delete this page?'),
                        'escape' => false
                    )
            ); ?>
        </li>
        <?php endif; ?>
        <li class="no-bg right last">
            <?= $this->link(
                '@admin_pages',
                $this->image($this->assetUrl('/images/icon/edit-list.png', false)) . ' '.$this->translate('back to pages'),
                array('escape' => false)
            ); ?>
        </li>
    </ul>

    <h2><?= $this->translate('Options') ?></h2>

    <div class="form-options-panel">

        <?= $this->form->template; ?>
        <?= $this->form->layout; ?>

        <div class="form-row" id="homepage-row">
            <label for="homepage"><?= $this->translate('Homepage') ?></label>
            <?= $this->form->homepage->setDecorators(array('ViewHelper', 'Errors')); ?>
            <?= $this->translate($this->form->homepage->getDescription()) ?>
        </div>

    </div>
    
</div>

</form>
