<h1>Page</h1>

<div class="form-container">
    <form action="<?= $this->url("/admin/page/$this->action") ?>" method="post" name="PageForm" id="PageForm">
        <?php if ($this->action === 'edit'): ?>
        <input type="hidden" name="id" value="<?= $this->page->getId() ?>">
        <?php endif; ?>
        <div class="form-row">
            <label for="title">Title</label>
            <input type="text" name="title" id="title" value="<?= $this->page->getTitle() ?>" />
        </div>

        <div class="form-row">
            <label for="slug">Slug</label>
            <input type="text" name="slug" id="slug" value="<?= $this->page->getSlug() ?>" />
        </div>

        <div class="form-row yui-skin-sam">
            <label for="body">Body</label>
            <div style="float: left;">
                <textarea name="body" id="body" style="width: 790px;"><?= $this->page->getBody() ?></textarea>
            </div>
            <div class="clear"></div>
            <div style="text-align: right;">
                <a href="#" onclick="showEditor();">show editor</a>
                &nbsp;|&nbsp;
                <a href="#" onclick="hideEditor();">hide editor</a>
            </div>
        </div>

        <?php if(0 < count($this->availableTemplates)) : ?>
        <div class="form-row">
            <label for="template">Template</label>
            <select name="template" id="template">
                <option value="null">Default</option>
                <?php foreach($this->availableTemplates as $template) : ?>
                <option value="<?= $template; ?>"><?= $template; ?></option>
                <?php endforeach;?>
            </select>
        </div>
        <?php endif;?>

        <?php if(0 < count($this->availableLayouts)) : ?>
        <div class="form-row">
            <label for="template">Layout</label>
            <select name="layout" id="layout">
                <option value="null">Default</option>
                <?php foreach($this->availableLayouts as $template) : ?>
                <option value="<?= $template; ?>"><?= $template; ?></option>
                <?php endforeach;?>
            </select>
        </div>
        <?php endif; ?>

        <div class="form-row">
            <label for="homepage">Homepage?</label>
            <input type="checkbox" name="homepage" id="homepage" value="1" />
        </div>

        <div class="form-row form-row-last">
            <input type="submit" name="PageFormSubmit" id="PageFormSubmit" value="Save" /> or <a href="/admin/pages">cancel</a>
        </div>

    </form>
</div>
<script src="<?= $this->url("/js/yui/build/container/container_core-min.js") ?>"></script>
<script src="<?= $this->url("/js/yui/build/menu/menu-min.js") ?>"></script>
<script src="<?= $this->url("/js/yui/build/button/button-min.js") ?>"></script>
<script src="<?= $this->url("/js/yui/build/editor/editor-min.js") ?>"></script>

<script type="text/javascript">
        var bodyEditorConfig = {
            //ptags: true,
            animate: true,
            dompath: true,
            focusAtStart: true,
            handleSubmit: true
        };

    //Now let's load the Editor..
    var bodyEditor = new YAHOO.widget.Editor('body', bodyEditorConfig);
    bodyEditor.render();

</script>
