<h1>Page</h1>

<div class="form-container">
    <form action="<?= $this->url("/admin/page/$this->action") ?>" method="post" name="PageForm" id="PageForm">
        <?php if ($this->action === 'edit'): ?>
        <input type="hidden" name="id" value="<?= $this->page->getId() ?>">
        <?php endif; ?>
        <div class="form-row">
            <label for="title">Title</label>
            <input type="text" name="title" id="title" value="<?= $this->page->getTitle() ?>" />
        </div>

        <div class="form-row">
            <label for="slug">Slug</label>
            <input type="text" name="slug" id="slug" value="<?= $this->page->getSlug() ?>" />
        </div>

        <div class="form-row yui-skin-sam">
            <label for="body">Body</label>
            <div style="float: left;">
                <textarea name="body" id="body" style="width: 790px;"><?= $this->page->getBody() ?></textarea>
            </div>
            <div class="clear"></div>
            <div style="text-align: right;">
                <a href="#" onclick="showEditor();">show editor</a>
                &nbsp;|&nbsp;
                <a href="#" onclick="hideEditor();">hide editor</a>
            </div>
        </div>

        <?php if(0 < count($this->availableTemplates)) : ?>
        <div class="form-row">
            <label for="template">Template</label>
            <select name="template" id="template">
                <option value="null">Default</option>
                <?php foreach($this->availableTemplates as $template) : ?>
                <option value="<?= $template; ?>" <?= $this->page->getTemplate() === $template ? 'selected="selected"' : '' ?>>
                    <?= $template; ?>
                </option>
                <?php endforeach;?>
            </select>
        </div>
        <?php endif;?>

        <?php if(0 < count($this->availableLayouts)) : ?>
        <div class="form-row">
            <label for="template">Layout</label>
            <select name="layout" id="layout">
                <option value="null">Default</option>
                <?php foreach($this->availableLayouts as $template) : ?>
                <option value="<?= $template; ?>" <?= $this->page->getLayout() === $template ? 'selected="selected"' : '' ?>>
                    <?= $template; ?>
                </option>
                <?php endforeach;?>
            </select>
        </div>
        <?php endif; ?>

        <div class="form-row">
            <label for="homepage">Homepage?</label>
            <input type="checkbox" name="homepage" id="homepage" value="1" <?= $this->page->getHomepage() !== null ? 'checked="checked"' : '' ?> />
        </div>

        <div class="form-row form-row-last">
            <input type="submit" name="PageFormSubmit" id="PageFormSubmit" value="Save" /> or <a href="/admin/pages">cancel</a>
        </div>

    </form>
</div>
<script type="text/javascript">
    _editor_url  = "<?= $this->url('/js/xinha/'); ?>"
    _editor_lang = "en";
</script>
<script type="text/javascript" src="<?= $this->url('/js/xinha/XinhaCore.js'); ?>"></script>
<script type="text/javascript">
    xinha_init = function() {
        xinha_editors = [ 'body' ];
        xinha_plugins = [
           'CharacterMap',
           'ContextMenu',
           'ListType',
           'Stylist',
           'Linker',
           'SuperClean',
           'TableOperations'
        ];

        // THIS BIT OF JAVASCRIPT LOADS THE PLUGINS, NO TOUCHING  :)
        if(!Xinha.loadPlugins(xinha_plugins, xinha_init)) return;

        xinha_config = new Xinha.Config();
        xinha_config.toolbar = [
            ["popupeditor"],
            ["separator","formatblock","fontname","fontsize","bold","italic","underline","strikethrough"],
            ["separator","forecolor","hilitecolor","textindicator"],
            ["separator","subscript","superscript"],
            ["linebreak","separator","justifyleft","justifycenter","justifyright","justifyfull"],
            ["separator","insertorderedlist","insertunorderedlist","outdent","indent"],
            ["separator","inserthorizontalrule","createlink","insertimage","inserttable"],
            ["linebreak","separator","undo","redo"], (Xinha.is_gecko ? [] : ["cut","copy","paste","overwrite","saveas"]),
            ["separator","killword","clearfonts","removeformat","toggleborders"],
            ["separator","htmlmode"]
        ];

        xinha_editors = Xinha.makeEditors(xinha_editors, xinha_config, xinha_plugins);

        Xinha.startEditors(xinha_editors);
    }

    Xinha._addEvent(window,'load', xinha_init);
</script>
