<?php
/**
 * Admin page form view
 * @package Fizzy
 * @subpackage Views
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.voidwalkers.nl/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@voidwalkers.nl so we can send you a copy immediately.
 *
 * @copyright Copyright (c) 2009 Voidwalkers (http://www.voidwalkers.nl)
 * @license http://www.voidwalkers.nl/license/new-bsd The New BSD License
 */
 ?>
<h1>Page</h1>

<div class="form-container">
    <form action="<?= $this->url("/admin/page/$this->action") ?>" method="post" name="PageForm" id="PageForm">
        <?php if ($this->action === 'edit'): ?>
        <input type="hidden" name="id" value="<?= $this->page->getId() ?>">
        <?php endif; ?>
        <div class="form-row">
            <label for="title">Title</label>
            <input type="text" name="title" id="title" value="<?= $this->page->getTitle() ?>" />
        </div>

        <div class="form-row">
            <label for="slug">Slug</label>
            <input type="text" name="slug" id="slug" value="<?= $this->page->getSlug() ?>" />
        </div>

        <div class="form-row yui-skin-sam">
            <label for="body">Body</label>
            <div>
                <textarea name="body" id="body" style="width: 100%;"><?= $this->page->getBody() ?></textarea>
            </div>

            <div class="clear"></div>
            <div style="text-align: right;" id="editor-toggle"></div>
        </div>

        <?php if(0 < count($this->availableTemplates)) : ?>
        <div class="form-row">
            <label for="template">Template</label>
            <select name="template" id="template">
                <option value="null">Default</option>
                <?php foreach($this->availableTemplates as $template) : ?>
                <option value="<?= $template; ?>" <?= $this->page->getTemplate() === $template ? 'selected="selected"' : '' ?>>
                    <?= $template; ?>
                </option>
                <?php endforeach;?>
            </select>
        </div>
        <?php endif;?>

        <?php if(0 < count($this->availableLayouts)) : ?>
        <div class="form-row">
            <label for="template">Layout</label>
            <select name="layout" id="layout">
                <option value="null">Default</option>
                <?php foreach($this->availableLayouts as $template) : ?>
                <option value="<?= $template; ?>" <?= $this->page->getLayout() === $template ? 'selected="selected"' : '' ?>>
                    <?= $template; ?>
                </option>
                <?php endforeach;?>
            </select>
        </div>
        <?php endif; ?>

        <div class="form-row">
            <label for="homepage">Homepage?</label>
            <input type="checkbox" name="homepage" id="homepage" value="1" <?= $this->page->getHomepage() !== null ? 'checked="checked"' : '' ?> />
        </div>

        <div class="form-row form-row-last">
            <input type="submit" name="PageFormSubmit" id="PageFormSubmit" value="Save" /> or <a href="/admin/pages">cancel</a>
        </div>

    </form>
</div>

<script type="text/javascript">
YUI().use('node-base', 'event', function(Y) {
    var toggleButton;
    
    // init tinyMCE
    function init() {
        tinyMCE.init({
            mode : "exact",
            elements: "body",
            theme : "advanced",
            theme_advanced_toolbar_location : "top",
            theme_advanced_toolbar_align : "left",
            theme_advanced_buttons1: "formatselect,fontselect,fontsizeselect,separator,forecolor,backcolor,separator,removeformat,undo,redo",
            theme_advanced_buttons2 : "bold,italic,underline,sub,sup,separator,justifyleft,justifycenter,justifyright,justifyfull,separator,bullist,numlist,separator,outdent,indent,blockquote,separator,link,unlink,image,separator,charmap,code,cleanup",
            theme_advanced_buttons3: "",
            theme_advanced_statusbar_location : "bottom",
            theme_advanced_resizing : true,
            theme_advanced_resize_horizontal : false
        });
        
        toggleButton = Y.Node.create('<a href="#" id="toggleButton">hide editor</a>');
        toggleButton.on('click', toggleEditor);
        Y.Node.one('#editor-toggle').insert(toggleButton);
    }
    
    var toggleEditor = function(id) {
        tinyMCE.execCommand('mceToggleEditor', false, 'body');
        if(tinyMCE.getInstanceById('body').isHidden()) {
            toggleButton.setContent('show editor');
        }
        else {
            toggleButton.setContent('hide editor');
        }
    }
     
    // Wait for DOM to finish
    Y.on("domready", init);
});





</script>

