<?php

/**
 * Block
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Block extends BaseBlock
{
    protected $_model = null;

    public function getFormElement()
    {
        $this->_loadModel();
        return $this->_model->getFormElement();
    }

    public function getModel()
    {
        $this->_loadModel();
        return $this->_model;
    }

    protected static function _getModelClass($type)
    {
        return ucfirst($type);
    }


    protected function _loadModel()
    {
        if ($this->_model === null) {
            $this->_model = self::loadModel($this->type, $this->content_id);
        }
    }

    public static function createBlock($page_id, $type)
    {
        $class = self::_getModelClass($type);
        $model = new $class();
        $model->save();

        $block = new self();
        $block->page_id = $page_id;
        $block->content_id = $model->id;
        $block->type = strtolower($type);
        $block->save();
        return $block;
    }

    public static function removeBlock($id)
    {
	    $query = Doctrine_Query::create()->from('Block')->where('id = ?', $id);
	    $block = $query->fetchOne();
	    if ($block) {
            $class = self::_getModelClass($block->type);
            $query = Doctrine_Query::create()->from($class)->where('id = ?', $block->content_id);
            $content = $query->fetchOne();
            if ($content) {
                $content->delete();
            }
            $block->delete();
	    }
    }

    public static function loadModel($type, $id)
    {
        $query = Doctrine_Query::create()->from(self::_getModelClass($type))
                ->where('id = ?', $id);
        return $query->fetchOne();
    }
}