<?php

/**
 * Image
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Image extends BaseImage implements Fizzy_Block_Interface
{

    public function getFormElement()
    {
        return new Fizzy_Form_Element_Image('block_image_'.$this->id, array(
            'value' => $this->filename,
        ));
    }
    public function getValue() 
    {
        return $this->filename;
    }
    public function setValue($value)
    {
        $this->filename = $value;
    }
}