<?php
require_once 'generated/BasePage.php';

/**
 * Page
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Page extends BasePage
{
    public function getTemplate()
    {
        if(empty($this->template)) {
            $application = Zend_Registry::get('config')->application->toArray();
            $this->template = $application['defaultTemplate'];
        }
        
        return $this->template;
    }

    /**
     * Override to return the default layout if none is set.
     * @return string
     */
    public function getLayout()
    {
        if(empty($this->layout)) {
            $application = Zend_Registry::get('config')->application->toArray();
            $this->layout = $application['defaultLayout'];
        }

        return $this->layout;
    }

    public function populate($array)
    {
        $this->title = $array['title'];
        $this->slug = $array['slug'];
        $this->body = $array['body'];
        $this->homepage = (boolean) $array['homepage'];
        
        if ('default' !== $array['template'])
            $this->template = $array['template'];
        
        $this->layout = $array['layout'];

        return $this;
    }

}
