<?php

/**
 * Post
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Post extends BasePost
{
    const PUBLISHED = 2;
    const PENDING_REVIEW = 1;
    const DRAFT = 0;

    public function isNew()
    {
        return empty($this->id);
    }

}