<?php

/**
 * Richtext
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Richtext extends BaseRichtext
{
    public function getFormElement()
    {
        return new Fizzy_Form_Element_Wysiwyg('block_richtext_'.$this->id, array(
            'value' => $this->body
        ));
    }

    public function setValue($value)
    {
        $this->body = $value;
    }

    public function getValue()
    {
        return $this->body;
    }
}