<?php

/**
 * Setting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Setting extends BaseSetting
{

    public static $_settings = null;

    public static function getAll($reload = false)
    {
        if (null === self::$_settings || $reload) {
            $settings = array();
            foreach (Doctrine_Core::getTable('Setting')->findAll() as $setting) {
                $settings[$setting->setting_key] = $setting;
            }
            self::$_settings = $settings;
        }

        return self::$_settings;
    }

    public static function getKey($key, $reload = false)
    {
        $settings = self::getAll($reload);

        return isset($settings[$key]) ? $settings[$key] : null;
    }

    public function isNew()
    {
        return empty($this->id);
    }

}