<?php
/**
 * Admin user form view
 * @package Fizzy
 * @subpackage Views
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.voidwalkers.nl/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@voidwalkers.nl so we can send you a copy immediately.
 *
 * @copyright Copyright (c) 2009 Voidwalkers (http://www.voidwalkers.nl)
 * @license http://www.voidwalkers.nl/license/new-bsd The New BSD License
 */
 ?>
<h1>User</h1>

<div class="form-container">
    <?php if (!empty($this->message)) : ?>
    <span class="error"><?= $this->message ?></span>
    <?php endif; ?>
    <form action="<?= $this->url("/admin/user/$this->action") ?>" method="post" name="UserForm" id="UserForm">
        <?php if ($this->action === 'edit'): ?>
        <input type="hidden" name="id" value="<?= $this->user->getId() ?>">
        <?php endif; ?>
        <div class="form-row">
            <label for="username">Username</label>
            <input type="text" name="username" id="username" value="<?= $this->user->getUsername() ?>" />
        </div>

        <div class="form-row">
            <label for="password">Password</label>
            <input type="password" name="password" id="password" value="" />
        </div>

        <div class="form-row">
            <label for="password2">Password (again)</label>
            <input type="password" name="password2" id="password2" value="" />
        </div>

        <div class="form-row form-row-last">
            <input type="submit" name="UserFormSubmit" id="UserFormSubmit" value="Save" /> or <a href="/admin/users">cancel</a>
        </div>

    </form>
</div>

