<?php
// file type image declarations

$images = array('png', 'jpg', 'jpeg', 'bmp', 'gif');

$types = array(
    'png' => $this->url('/admin/images/icon/page_white_picture.png'),
    'jpg' => $this->url('/admin/images/icon/page_white_picture.png'),
    'jpeg' => $this->url('/admin/images/icon/page_white_picture.png'),
    'bmp' => $this->url('/admin/images/icon/page_white_picture.png'),
    'gif' => $this->url('/admin/images/icon/page_white_picture.png'),
    'doc' => $this->url('/admin/images/icon/page_white_word.png'),
    'docx' => $this->url('/admin/images/icon/page_white_word.png'),
    'xls' => $this->url('/admin/images/icon/page_white_excel.png'),
    'ppt' => $this->url('/admin/images/icon/page_white_powerpoint.png'),
    'pdf' => $this->url('/admin/images/icon/page_white_text.png'),
    'flv' => $this->url('/admin/images/icon/page_white_flash.png'),
    'zip' => $this->url('/admin/images/icon/page_white_zip.png'),
    'rar' => $this->url('/admin/images/icon/page_white_zip.png'),
    'txt' => $this->url('/admin/images/icon/page_white_text.png'),
);
?>
<h1 class="header">Media</h1>

<p>
    On this page you find the media available within Fizzy. With the form on the 
    bottom of the page you are able to add files to Fizzy that you can use in 
    your pages.
</p>

<div id="uploaded-files">
    <h2>Files overview</h2>
    
    <div class="files-menubar">
        <ul>
            <li><a href="<?= $this->url('/admin/media') ?>">List view</a></li>
        </ul>
        <div class="clear"></div>
    </div>
    <div class="files-container">
        <?php foreach($this->files as $fileInfo) : ?>
        <div class="thumbnail">
            <div class="controls">
                <a href="<?= $this->url('/uploads/' . $fileInfo->basename); ?>" target="_blank" title="View file"><?= $this->img('/admin/images/icon/view.png'); ?></a>
                <?php if(is_writable($this->uploadFolder)) : ?>
                <?= $this->link_confirm('/admin/media/delete/' . urlencode($fileInfo->basename), $this->img('/admin/images/icon/delete.png'), "Are you sure you want to delete {$fileInfo->basename}?", array('title' => 'Delete file')); ?>
                <?php endif; ?>
            </div>
            <?php if (in_array($fileInfo->type, $images)): ?>
                <img class="thumbnail" src="<?= $this->url('/uploads/' . $fileInfo->basename); ?>" alt="<?= $fileInfo->basename ?>" />
            <?php else: ?>
                <img class="icon" src="<?= (array_key_exists($fileInfo->type, $types)) ? $types[$fileInfo->type] : $this->url('/admin/images/icon/page.png'); ?>" alt="" />
            <?php endif; ?>
            
            <div class="filename">
                <?php if (strlen($fileInfo->basename) > 14):?>
                    <?= substr($fileInfo->basename, 0, 14); ?>...
                <?php else: ?>
                    <?= $fileInfo->basename ?>
                <?php endif; ?>
            </div>
            <div class="size">
                <?php if($fileInfo->size < 1024) : ?>
                <?= round($fileInfo->size, 2); ?> b
                <?php elseif((1024*1024) > $fileInfo->size) : ?>
                <?= round($fileInfo->size / 1024, 2); ?> KB
                <?php else : ?>
                <?= round($fileInfo->size / (1024*1024), 2); ?> MB
                <?php endif; ?>
            </div>
        </div>
        <?php endforeach; ?>
    
        
    </div>
</div>

<div id="upload-form">
    <h2 class="header">Upload</h2>
    <p>
        Upload a new file by selecting it on your machine. Check the box if 
        you want to overwrite a file that already exists with the same name.
        <br />
        
    </p>
    <?php if(is_writable($this->uploadFolder)) : ?>
    <form action="<?= $this->url('/admin/media'); ?>" method="post" enctype="multipart/form-data">
        <?php if(isset($this->messages) && !empty($this->messages)) : ?>
        <div class="message error">
            <ul>
            <?php foreach($this->messages as $message) : ?>
                <li><?= $message ?></li>
            <?php endforeach; ?>
            </ul>
         
        </div>
        <?php endif; ?>
        
        <div>
            <input name="upload" type="file" /><br />
            <small>The maximum size for a file upload is <strong><?= str_replace(array('K', 'M', 'G'), array(' KB', ' MB', ' GB'), $this->upload_max_filesize); ?></strong>.</small>
        </div>
        <div>
            <label for="overwrite">Overwrite existing file?</label>
            <input type="checkbox" name="overwrite" value="1" />
        </div>
        <div>
           <input type="submit" value="Upload" />
       </div>
    </form>
    <?php else : ?>
    <div class="message notice">
        <p>
            The upload directory found in the Fizzy configuration is not 
            writable. Upload functionality will be disabled until it is made 
            writable.
        </p>
    </div>
    <?php endif; ?>
</div>
