User:
  columns:
    id: { type: integer(4), primary: true, autoincrement: true }
    username: string(150)
    password: string(150)
    encryption: string(10)

Page:
  columns:
    id: { type: integer(4), primary: true, autoincrement: true }
    title: string(255)
    slug: string(255)
    body: string
    homepage: boolean
    layout: string(150)
    template: string(150)

Setting:
  columns:
    id: { type: integer(4), primary: true, autoincrement: true }
    component: string(50)
    key: string(50)
    value: string(255)
    label: string(150)
    description: text