<h1>Configuration</h1>
<p>
    The configuration below is loaded when Fizzy starts. For an overview of the
    fizzy configuration settings see <a href="http://project.voidwalkers.nl/wiki/fizzy/Configuration">the manual</a>. <br />
    These settings can be changed in the files found under 
    <span class="code-inline"><?= Fizzy_Config::getInstance()->getPath('configs') ?></span>.
</p>

<a href="#" id="expand">Expand all</a> | <a href="#" id="collapse">Collapse all</a>
<div id="config-browser">
<ul>
    <?= arrayToList($this->configuration); ?>
</ul>
</div>

<script type="text/javascript" src="<?= $this->url('/js/yui/build/treeview/treeview-min.js'); ?>"></script>
<script type="text/javascript">
    var treeInit = function() {
        var tree = new YAHOO.widget.TreeView("config-browser");
        tree.render();
        
        YAHOO.util.Event.on("collapse", "click", function(e) {
                tree.collapseAll();
                YAHOO.util.Event.preventDefault(e);
        });

        YAHOO.util.Event.on("expand", "click", function(e) {
                tree.expandAll();
                YAHOO.util.Event.preventDefault(e);
        });

    };
    YAHOO.util.Event.onDOMReady(treeInit);
</script>


<?php
function arrayToList($array) {
    
    foreach($array as $key => $value) {
        $list .= "<li>\n";
        $list .= "{$key}\n";
        $list .= "<ul>\n";
        
        if(is_array($value)) {
            $list .= arrayToList($value);
        }
        else {
            $list .= "<li>{$value}</li>\n";
        }

        $list .= "</ul>\n";
        $list .= "</li>\n";
    }

    return $list;
}
?>
