<h1>Configuration</h1>
<p>
    The configuration below is loaded when Fizzy starts. For an overview of the
    fizzy configuration settings see <a href="http://project.voidwalkers.nl/wiki/fizzy/Configuration">the manual</a>. <br />
    These settings can be changed in the files found under 
    <span class="code-inline"><?= Fizzy_Config::getInstance()->getPath('configs') ?></span>.
</p>

<ul id="config-browser">
    <?= arrayToList($this->configuration); ?>
</ul>



<?php
function arrayToList($array) {
    
    foreach($array as $key => $value) {
        $list .= "\t<li class=\"item\">\n";
        $list .= "\t\t<span class=\"folder\">{$key}</span>\n";
        $list .= "\t\t<ul>\n";
        
        if(is_array($value)) {
            $list .= arrayToList($value);
        }
        else {
            $list .= "\t\t<li><span class=\"file\">{$value}</span></li>\n";
        }

        $list .= "\t\t</ul>\n";
        $list .= "\t</li>\n";
    }

    return $list;
}
?>

<script src="/js/jquery-1.3.2.min.js" type="text/javascript"></script>
<script src="/js/jquery.treeview.min.js" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function() {
    $("#config-browser").treeview({});
});
</script>