<?php
/**
 * Admin menu view
 * @package Fizzy
 * @subpackage Views
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.voidwalkers.nl/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@voidwalkers.nl so we can send you a copy immediately.
 *
 * @copyright Copyright (c) 2009 Voidwalkers (http://www.voidwalkers.nl)
 * @license http://www.voidwalkers.nl/license/new-bsd The New BSD License
 */
 ?>
<h1 class="header">Menu</h1>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js" type="text/javascript"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js" type="text/javascript"></script>

<p>
    Drag the available items to the menu items container to add them to the
    site menu. Change the order of the menu items to sort them.
</p>

<div>

    <div class="menu-container">
        <h2>Menu items</h2>
        <div class="item-list-container" id="menu-items-container">
            <ul id="menu-items" class="sortable-list" />
        </div>
    </div>

    <div class="menu-container">
        <h2>Available items</h2>
        <div class="item-list-container" id="available-items-container">
            <ul id="available-items" class="sortable-list">
                <?php foreach($this->pages as $page) : ?>
                <li class="ui-state-default"><?= $page->title; ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>

    <div class="clear"></div>

    <div>
        <input type="submit" value="Save" />
    </div>

</div>

<script type="text/javascript">
    $(document).ready(function() {
        $("#available-items, #menu-items").sortable({
            placeholder: 'ui-state-highlight',
            connectWith: '.sortable-list',
            change: function(event, ui) {
            }
        }).disableSelection();
    });
</script>