<h1>Pages</h1>
<div>
    <table border="1">
        <thead>
            <tr>
                <td>Title</td>
                <td>Slug</td>
                <td>&nbsp;</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->pages as $page) : ?>
            <tr>
                <td><?= $page->title ?></td>
                <td><?= $page->slug ?></td>
                <td>
                    <?= $this->link("/page/{$page->slug}", $this->img('/images/icon/view.png', array('alt' => 'View icon')), array('target' => '_blanc')); ?>
                    <?= $this->link("/page/edit/{$this->id}", $this->img('/images/icon/edit.png')); ?>
                    <?= $this->link("/page/delete/{$this->id}", $this->img('/images/icon/sign_remove.png')); ?>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <p>
        <?= $this->link('/admin/pages/add', $this->img('/images/icon/add.png') . ' Add Page'); ?>
    </p>
</div>