<?php
/**
 * Admin pages view
 * @package Fizzy
 * @subpackage Views
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.voidwalkers.nl/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@voidwalkers.nl so we can send you a copy immediately.
 *
 * @copyright Copyright (c) 2009 Voidwalkers (http://www.voidwalkers.nl)
 * @license http://www.voidwalkers.nl/license/new-bsd The New BSD License
 */
 ?>
<h1>Pages</h1>
<div>
    <table class="data-table">
        <thead>
            <tr>
                <td>Title</td>
                <td>Slug</td>
                <td>&nbsp;</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->pages as $page) : ?>
            <tr>
                <td><?= $page->title ?></td>
                <td><?= $page->slug ?></td>
                <td style="width: 100px;">
                    <?= $this->link("/page/{$page->slug}", $this->img('/images/icon/view.png', array('alt' => 'View icon')), array('target' => '_blanc')); ?>
                    <?= $this->link("/admin/page/edit/{$page->id}", $this->img('/images/icon/edit.png')); ?>
                    <?= $this->link("/admin/page/delete/{$page->id}", $this->img('/images/icon/sign_remove.png')); ?>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <p>
        <?= $this->link('/admin/page/add', $this->img('/images/icon/add.png') . ' Add Page'); ?>
    </p>
</div>