<?php
/**
 * Admin users view
 * @package Fizzy
 * @subpackage Views
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.voidwalkers.nl/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@voidwalkers.nl so we can send you a copy immediately.
 *
 * @copyright Copyright (c) 2009 Voidwalkers (http://www.voidwalkers.nl)
 * @license http://www.voidwalkers.nl/license/new-bsd The New BSD License
 */
 ?>
<h1>Users</h1>
<div>
    <table class="data-table">
        <thead>
            <tr>
                <td>Username</td>
                <td>&nbsp;</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->users as $user) : ?>
            <tr>
                <td><?= $user->username; ?></td>
                <td>
                    <a href="<?= $this->url("/admin/user/edit/$user->getId()") ?>" title="Edit user"><img src="<?= $this->url("/images/icon/edit.png") ?>" alt="edit icon" /></a>
                    <a href="<?= $this->url("/admin/user/delete/$user->getId()") ?>" title="Delete user"><img src="<?= $this->url("/images/icon/sign_remove.png") ?>" alt="delete icon" /></a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <p>
        <?= $this->link('/admin/user/add', $this->img('/images/icon/add.png') . ' Add User'); ?>
    </p>
</div>
