<h1>Users</h1>
<div>
    <table class="data-table">
        <thead>
            <tr>
                <td>Username</td>
                <td>&nbsp;</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->users as $user) : ?>
            <tr>
                <td><?= $user->username; ?></td>
                <td>
                    <a href="<?= $this->url("/admin/user/edit/$user->id") ?>" title="Edit user"><img src="<?= $this->url("/images/icon/edit.png") ?>" alt="edit icon" /></a>
                    <a href="<?= $this->url("/admin/user/delete/$user->id") ?>" title="Delete user"><img src="<?= $this->url("/images/icon/sign_remove.png") ?>" alt="delete icon" /></a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <p>
        <?= $this->link('/admin/user/add', $this->img('/images/icon/add.png') . ' Add User'); ?>
    </p>
</div>