<?php foreach ($this->comments as $comment): ?>
<?php
$thread = $comment->getThreadModel();
?>
<div class="comment">
    <div class="avatar">
        <img src="http://www.gravatar.com/avatar/<?= md5(trim(strtolower($comment->email))) ?>?s=80" alt="<?= $comment->name ?>" />
    </div>
    <div class="content">
        <div class="author-info">
            <span class="gray1">From</span> <?= $comment->name ?>
            <?= (!empty($thread)) ? '<span class="gray1">on</span> '.
            $this->link('@admin_comments_topic?id=' . $comment->post_id,$thread->label()) : '' ?>
        </div>
        <div class="comment-body">
                <?= $comment->body ?>
        </div>
        <div class="actions">
            <ul>
                <li>
                    <?= $this->link('/fizzy/comment/edit/' . $comment->id . '?back=' . $this->back, 'Edit', array(
                        'class' => 'c3button'
                    )) ?>
                </li>
                <li>
                    <?php if ($comment->isSpam()) : ?>
                        <?= $this->link('/fizzy/comment/ham/' . $comment->id . '?back=' . $this->back, 'Not spam', array(
                            'class' => 'c3button'
                        )) ?>
                    <?php else: ?>
                        <?= $this->link('/fizzy/comment/spam/' . $comment->id . '?back=' . $this->back, 'Spam', array(
                            'class' => 'c3button'
                        )) ?>
                    <?php endif; ?>
                </li>
                <li><?= $this->link(
                                '/fizzy/comment/delete/' . $comment->id . '?back=' . $this->back,
                                'Delete',
                                array(
                                'class' => 'delete c3button',
                                'confirm' => 'Are you sure you want to delete this comment?',
                                )
                        ); ?>
                </li>
            </ul>
        </div>
    </div>
    <div class="clear"></div>
</div>
<?php endforeach; ?>
