<form action="<?= $this->form->getAction(); ?>" method="post">

<div id="content-panel">

    <h2>
        Edit Comment
    </h2>

    <div class="form-panel">
            <?= $this->form->name; ?>
            <?= $this->form->email; ?>
            <?= $this->form->website; ?>
            <?= $this->form->body; ?>
    </div>
</div>
<div id="sidebar-panel">

    <h2>Actions</h2>

    <ul class="actions">
        <li class="last">
            <input type="submit" value="Save" />
        </li>
    </ul>

    <hr />

    <ul class="actions">
        <li class="no-bg right">
            <?= $this->linkConfirm(
                    '/fizzy/comment/delete/' . $this->comment->id,
                    $this->img('fizzy_assets/images/icon/document--minus.png') . ' delete comment',
                    'Are you sure you want to delete this comment?',
                    array('class' => 'delete')
            ); ?>
        </li>
        <li class="no-bg right last">
            <?= $this->link(
                '/fizzy/comments/topic/' . $this->comment->post_id,
                $this->img('/fizzy_assets/images/icon/edit-list.png') . ' back to comments'
            ); ?>
        </li>
    </ul>

</div>

</form>

