<form action="<?= $this->form->getAction(); ?>" method="post">

<div id="content-panel">

    <h2>
        <?= $this->translate('Edit comment') ?>
    </h2>

    <div class="form-panel">
            <?= $this->form->name; ?>
            <?= $this->form->email; ?>
            <?= $this->form->website; ?>
            <?= $this->form->body; ?>
    </div>
</div>
<div id="sidebar-panel">

    <h2><?= $this->translate('Actions') ?></h2>

    <ul class="actions">
        <li class="last">
            <input type="submit" value="<?= $this->translate('Save') ?>" />
        </li>
    </ul>

    <hr />

    <ul class="actions">
        <li class="no-bg right">
            <?= $this->link(
                    '@admin_comments_delete?id=' . $this->comment->id,
                    $this->image($this->assetUrl('/images/icon/document--minus.png', false)) . ' '.$this->translate('delete comment'),
                    array(
                        'class' => 'delete',
                        'confirm' => $this->translate('Are you sure you want to delete this comment?'),
                        'escape' => false
                    )
            ); ?>
        </li>
        <li class="no-bg right last">
            <?= $this->link(
                '@admin_comments_topic?id=' . $this->comment->post_id,
                $this->image($this->assetUrl('/images/icon/edit-list.png', false)) . ' '.$this->translate('back to comments'),
                array(
                    'escape' => false
                )
            ); ?>
        </li>
    </ul>

</div>

</form>

