<div id="content-panel">

    <h2>Comments overview</h2>

    <table class="data" style="width: 400px;">
        <tbody>
            <tr>
                <td><a href="<?= $this->baseUrl('/fizzy/comments/list') ?>">Total comments</a></td>
                <td><?= $this->totalComments ?></td>
            </tr>
            <tr>
                <td><a href="<?= $this->baseUrl('/fizzy/comments/spam') ?>">Spam</a></td>
                <td><?= $this->spamComments ?></td>
            </tr>
        </tbody>
    </table>

    <br>

    <h2>Latest comments</h2>

    <?php foreach ($this->paginator->getCurrentItems() as $comment): ?>
    <div class="comment">
        <div class="avatar">
            <img src="http://www.gravatar.com/avatar/<?= md5(trim(strtolower($comment->email))) ?>?s=80" alt="<?= $comment->name ?>" />
        </div>
        <div class="content">
            <div class="author-info">
                From <?= $comment->name ?>
            </div>
            <div class="comment-body">
                    <?= $comment->body ?>
            </div>
            <div class="actions">
                <ul>
                    <li><a href="<?= $this->baseUrl('/fizzy/comment/edit/' . $comment->id . '?back=dashboard') ?>">Edit</a></li>
                    <li>
                            <?php if ($comment->isSpam()) : ?>
                        <a href="<?= $this->baseUrl('/fizzy/comment/ham/' . $comment->id . '?back=dashboard') ?>">Not spam</a>
                            <?php else: ?>
                        <a href="<?= $this->baseUrl('/fizzy/comment/spam/' . $comment->id . '?back=dashboard') ?>">Spam</a>
                            <?php endif; ?>
                    </li>
                    <li><?= $this->linkConfirm(
                                    '/fizzy/comment/delete/' . $comment->id . '?back=dashboard',
                                    'Delete',
                                    'Are you sure you want to delete this comment?',
                                    array('class' => 'delete')
                            ); ?>
                    </li>
                </ul>
            </div>
        </div>
        <div class="clear"></div>
    </div>
    <?php endforeach; ?>

    <?= $this->paginationControl($this->paginator, 'All', '_pagination.phtml') ?>

</div>

<div id="sidebar-panel">

</div>