<div id="content-panel">

    <h2>Latest comments</h2>

    <?= $this->partial('comments/_comments.phtml', array(
        'comments' => $this->paginator->getCurrentItems(),
        'back' => 'dashboard'
    )) ?>

    <?= $this->paginationControl($this->paginator, 'All', '_pagination.phtml') ?>

</div>

<div id="sidebar-panel">
    <h2>Comments overview</h2>

    <table class="data">
        <tbody>
            <tr>
                <td><a href="<?= $this->baseUrl('/fizzy/comments/list') ?>">Total comments</a></td>
                <td><?= $this->totalComments ?></td>
            </tr>
            <tr>
                <td><a href="<?= $this->baseUrl('/fizzy/comments/spam') ?>">Spam</a></td>
                <td><?= $this->spamComments ?></td>
            </tr>
        </tbody>
    </table>
</div>