<div id="content-panel">

    <h2>Discussions</h2>
    <div>
        <table class="data" id="pages-table">
            <thead>
                <tr>
                    <td>&nbsp;</td>
                    <td>Title</td>
                    <td>Number comments</td>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->paginator->getCurrentItems() as $topic): ?>
                <tr>
                    <td class="controls">
                        
                    </td>
                    <td><?= $this->link('@admin_comments_topic?id=' . $topic->post_id, $topic->getThreadModel()->label()) ?></td>
                    <td><?= $topic->getNumberTopicComments() ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <?= $this->paginationControl($this->paginator, 'All', '_pagination.phtml') ?>

    </div>

</div>

<div id="sidebar-panel">

</div>
